#!/usr/bin/env bash
set -euo pipefail

# ---------------------------------------------------------------------------
# Adams2019 autotune wrapper for PRISM generators.
#
# This wrapper calls the installed Halide adams2019_autotune_loop.sh (via
# HALIDE_TOOLS_DIR) and relies on the CMake target `prism_autotune_setup`
# to create build/autotune/* directories.
# ---------------------------------------------------------------------------

# Repo root (one level above misc/).
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

# --------------------------- USER CONFIG -----------------------------------
# Build directory (override by exporting BUILD_DIR).
BUILD_DIR="${BUILD_DIR:-${PROJECT_ROOT}/build}"

# Generator executable built by CMake (optional override).
GENERATOR="${GENERATOR:-}"

# Pipeline selection (required).
if [[ $# -gt 2 ]]; then
  echo "Usage: $(basename "$0") <pipeline_base> <tx|rx>"
  exit 1
fi
PIPELINE_BASE="${PIPELINE_BASE:-}"
PIPELINE_DIR="${PIPELINE_DIR:-}"
if [[ $# -eq 2 ]]; then
  PIPELINE_BASE="$1"
  PIPELINE_DIR="$2"
elif [[ $# -eq 1 ]]; then
  echo "Usage: $(basename "$0") <pipeline_base> <tx|rx>"
  exit 1
fi
if [[ -n "${PIPELINE_BASE}" && -n "${PIPELINE_DIR}" ]]; then
  case "${PIPELINE_DIR}" in
    tx|rx) ;;
    *)
      echo "PIPELINE_DIR must be tx or rx."
      exit 1
      ;;
  esac
  PIPELINE="${PIPELINE_BASE}_${PIPELINE_DIR}"
elif [[ -z "${PIPELINE}" ]]; then
  echo "Pipeline is required (e.g., apm_dsss tx)."
  echo "Usage: $(basename "$0") <pipeline_base> <tx|rx>"
  exit 1
fi

if [[ -z "${GENERATOR}" ]]; then
  _base="${PIPELINE_BASE}"
  if [[ -z "${_base}" ]]; then
    if [[ -n "${PIPELINE}" ]]; then
      _base="${PIPELINE%_tx}"
      _base="${_base%_rx}"
    fi
  fi
  if [[ -z "${_base}" ]]; then
    echo "Pipeline base is required; set PIPELINE_BASE or GENERATOR explicitly."
    exit 1
  fi
  GENERATOR="${BUILD_DIR}/example_${_base}_autotune"
fi

# Halide target string.
HALIDE_TARGET="${HALIDE_TARGET:-host}"

# Baseline weights file.
WEIGHTS_FILE="${WEIGHTS_FILE:-${PROJECT_ROOT}/misc/adams2019_baseline.weights}"

# Autotune environment generated by CMake.
AUTOTUNE_DIR="${AUTOTUNE_DIR:-${BUILD_DIR}/autotune}"
AUTOSCHED_BIN="${AUTOSCHED_BIN:-${AUTOTUNE_DIR}/autosched_bin}"
HALIDE_DISTRIB_PATH="${HALIDE_DISTRIB_PATH:-${AUTOTUNE_DIR}/halide_dist}"
HALIDE_TOOLS_DIR="${HALIDE_TOOLS_DIR:-${AUTOTUNE_DIR}/tools}"

if [[ ! -f "${AUTOTUNE_DIR}/env.sh" ]]; then
  echo "Autotune env not found: ${AUTOTUNE_DIR}/env.sh"
  echo "Run: cmake --build ${BUILD_DIR} --target prism_autotune_setup"
  exit 1
fi

# shellcheck disable=SC1090
source "${AUTOTUNE_DIR}/env.sh"
AUTOSCHED_BIN="${AUTOSCHED_BIN:-${AUTOTUNE_DIR}/autosched_bin}"
HALIDE_DISTRIB_PATH="${HALIDE_DISTRIB_PATH:-${AUTOTUNE_DIR}/halide_dist}"
HALIDE_TOOLS_DIR="${HALIDE_TOOLS_DIR:-${AUTOTUNE_DIR}/tools}"
SAMPLES_OUT="${SAMPLES_OUT:-${AUTOTUNE_DIR}/samples/${PIPELINE}_adams2019}"

# Optional generator args sets (space-delimited sets, semicolon-delimited args).
GENERATOR_ARGS_SETS="${GENERATOR_ARGS_SETS:-}"

# ---------------------------------------------------------------------------
# Sanity checks
# ---------------------------------------------------------------------------
if [[ ! -x "${GENERATOR}" ]]; then
  echo "Generator not found or not executable: ${GENERATOR}"
  echo "Build it with: cmake --build ${BUILD_DIR} --target $(basename "${GENERATOR}")"
  exit 1
fi
if [[ ! -f "${WEIGHTS_FILE}" ]]; then
  echo "Weights file not found: ${WEIGHTS_FILE}"
  exit 1
fi
if [[ ! -d "${AUTOSCHED_BIN}" || ! -d "${HALIDE_DISTRIB_PATH}" ]]; then
  echo "Autotune environment not found."
  echo "Run: cmake --build ${BUILD_DIR} --target prism_autotune_setup"
  exit 1
fi
if [[ -z "${HALIDE_TOOLS_DIR}" ]]; then
  HALIDE_TOOLS_DIR="${HALIDE_DISTRIB_PATH}/tools"
fi
LOOP_SCRIPT="${HALIDE_TOOLS_DIR}/adams2019_autotune_loop.sh"
if [[ ! -x "${LOOP_SCRIPT}" ]]; then
  echo "Loop script not found: ${LOOP_SCRIPT}"
  echo "Run: cmake --build ${BUILD_DIR} --target prism_autotune_setup"
  exit 1
fi

mkdir -p "${SAMPLES_OUT}"

# ---------------------------------------------------------------------------
# Run autotune
# ---------------------------------------------------------------------------
if [[ -n "${GENERATOR_ARGS_SETS}" ]]; then
  "${LOOP_SCRIPT}" \
    "${GENERATOR}" \
    "${PIPELINE}" \
    "${HALIDE_TARGET}" \
    "${WEIGHTS_FILE}" \
    "${AUTOSCHED_BIN}" \
    "${HALIDE_DISTRIB_PATH}" \
    "${SAMPLES_OUT}" \
    "${GENERATOR_ARGS_SETS}"
else
  "${LOOP_SCRIPT}" \
    "${GENERATOR}" \
    "${PIPELINE}" \
    "${HALIDE_TARGET}" \
    "${WEIGHTS_FILE}" \
    "${AUTOSCHED_BIN}" \
    "${HALIDE_DISTRIB_PATH}" \
    "${SAMPLES_OUT}"
fi
