#!/usr/bin/env bash
set -euo pipefail

# ---------------------------------------------------------------------------
# Anderson2021 autotune wrapper for PRISM generators.
#
# This wrapper calls the installed Halide anderson2021_autotune_loop.sh
# (via HALIDE_TOOLS_DIR). Use it with the CMake target
# `prism_autotune_setup` to prepare build/autotune/*.
# ---------------------------------------------------------------------------

# Repo root (one level above misc/).
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

# --------------------------- USER CONFIG -----------------------------------
# Build directory (override by exporting BUILD_DIR).
BUILD_DIR="${BUILD_DIR:-${PROJECT_ROOT}/build}"

# Generator executable built by CMake (optional override).
GENERATOR="${GENERATOR:-}"

# Pipeline selection (required).
if [[ $# -gt 2 ]]; then
  echo "Usage: $(basename "$0") <pipeline_base> <tx|rx>"
  exit 1
fi
PIPELINE_BASE="${PIPELINE_BASE:-}"
PIPELINE_DIR="${PIPELINE_DIR:-}"
if [[ $# -eq 2 ]]; then
  PIPELINE_BASE="$1"
  PIPELINE_DIR="$2"
elif [[ $# -eq 1 ]]; then
  echo "Usage: $(basename "$0") <pipeline_base> <tx|rx>"
  exit 1
fi
if [[ -n "${PIPELINE_BASE}" && -n "${PIPELINE_DIR}" ]]; then
  case "${PIPELINE_DIR}" in
    tx|rx) ;;
    *)
      echo "PIPELINE_DIR must be tx or rx."
      exit 1
      ;;
  esac
  PIPELINE="${PIPELINE_BASE}_${PIPELINE_DIR}"
elif [[ -z "${PIPELINE}" ]]; then
  echo "Pipeline is required (e.g., apm_dsss tx)."
  echo "Usage: $(basename "$0") <pipeline_base> <tx|rx>"
  exit 1
fi

if [[ -z "${GENERATOR}" ]]; then
  _base="${PIPELINE_BASE}"
  if [[ -z "${_base}" ]]; then
    if [[ "${PIPELINE}" == apm_basic_* ]]; then
      _base="apm_basic"
    elif [[ "${PIPELINE}" == apm_dsss_* ]]; then
      _base="apm_dsss"
    fi
  fi
  case "${_base}" in
    apm_basic)
      GENERATOR="${BUILD_DIR}/example_apm_basic_autotune"
      ;;
    apm_dsss)
      GENERATOR="${BUILD_DIR}/example_apm_dsss_autotune"
      ;;
    *)
      echo "Unknown pipeline base; set GENERATOR explicitly."
      exit 1
      ;;
  esac
fi

# Halide target string (GPU targets required for Anderson2021).
HALIDE_TARGET="${HALIDE_TARGET:-}"
if [[ -z "${HALIDE_TARGET}" ]]; then
  if [[ "$(uname -s)" == "Darwin" ]]; then
    HALIDE_TARGET="host-metal"
  else
    HALIDE_TARGET="host"
  fi
fi
if [[ "${HALIDE_TARGET}" != *"metal"* && "${HALIDE_TARGET}" != *"cuda"* &&
      "${HALIDE_TARGET}" != *"opencl"* ]]; then
  if [[ "$(uname -s)" == "Darwin" ]]; then
    HALIDE_TARGET="${HALIDE_TARGET}-metal"
    echo "HALIDE_TARGET missing GPU feature; auto-adding -metal => ${HALIDE_TARGET}"
  else
    echo "HALIDE_TARGET must include a GPU feature for Anderson2021 (e.g., host-cuda or host-opencl)."
    exit 1
  fi
fi

# Baseline weights file.
WEIGHTS_FILE="${WEIGHTS_FILE:-${PROJECT_ROOT}/misc/anderson2021_baseline.weights}"

# Autotune environment generated by CMake.
AUTOTUNE_DIR="${AUTOTUNE_DIR:-${BUILD_DIR}/autotune}"
AUTOSCHED_BIN="${AUTOSCHED_BIN:-${AUTOTUNE_DIR}/autosched_bin}"
HALIDE_DISTRIB_PATH="${HALIDE_DISTRIB_PATH:-${AUTOTUNE_DIR}/halide_dist}"
HALIDE_TOOLS_DIR="${HALIDE_TOOLS_DIR:-${AUTOTUNE_DIR}/tools}"
HALIDE_BUILD_DIR="${HALIDE_BUILD_DIR:-${AUTOTUNE_DIR}/halide_build}"

if [[ ! -f "${AUTOTUNE_DIR}/env.sh" ]]; then
  echo "Autotune env not found: ${AUTOTUNE_DIR}/env.sh"
  echo "Run: cmake --build ${BUILD_DIR} --target prism_autotune_setup"
  exit 1
fi

# shellcheck disable=SC1090
source "${AUTOTUNE_DIR}/env.sh"
AUTOSCHED_BIN="${AUTOSCHED_BIN:-${AUTOTUNE_DIR}/autosched_bin}"
HALIDE_DISTRIB_PATH="${HALIDE_DISTRIB_PATH:-${AUTOTUNE_DIR}/halide_dist}"
HALIDE_TOOLS_DIR="${HALIDE_TOOLS_DIR:-${AUTOTUNE_DIR}/tools}"
HALIDE_BUILD_DIR="${HALIDE_BUILD_DIR:-${AUTOTUNE_DIR}/halide_build}"
SAMPLES_OUT="${SAMPLES_OUT:-${AUTOTUNE_DIR}/samples/${PIPELINE}_anderson2021}"

# Parallelism and train-only settings.
PARALLELISM="${PARALLELISM:-32}"
TRAIN_ONLY="${TRAIN_ONLY:-0}"

# Optional generator args sets.
GENERATOR_ARGS_SETS="${GENERATOR_ARGS_SETS:-}"


# ---------------------------------------------------------------------------
# Sanity checks
# ---------------------------------------------------------------------------
if [[ ! -x "${GENERATOR}" ]]; then
  echo "Generator not found or not executable: ${GENERATOR}"
  echo "Build it with: cmake --build ${BUILD_DIR} --target $(basename "${GENERATOR}")"
  exit 1
fi
if [[ ! -f "${WEIGHTS_FILE}" ]]; then
  echo "Weights file not found: ${WEIGHTS_FILE}"
  exit 1
fi
if [[ ! -d "${AUTOSCHED_BIN}" || ! -d "${HALIDE_DISTRIB_PATH}" ]]; then
  echo "Autotune environment not found."
  echo "Run: cmake --build ${BUILD_DIR} --target prism_autotune_setup"
  exit 1
fi
if [[ -z "${HALIDE_TOOLS_DIR}" ]]; then
  HALIDE_TOOLS_DIR="${HALIDE_DISTRIB_PATH}/tools"
fi
LOOP_SCRIPT="${HALIDE_TOOLS_DIR}/anderson2021_autotune_loop.sh"
if [[ ! -x "${LOOP_SCRIPT}" ]]; then
  echo "Loop script not found: ${LOOP_SCRIPT}"
  echo "Run: cmake --build ${BUILD_DIR} --target prism_autotune_setup"
  exit 1
fi
if [[ ! -d "${HALIDE_BUILD_DIR}" ]]; then
  echo "HALIDE_BUILD_DIR not found: ${HALIDE_BUILD_DIR}"
  echo "Run: cmake --build ${BUILD_DIR} --target prism_autotune_setup"
  exit 1
fi

mkdir -p "${SAMPLES_OUT}"

# If CMake generated a fake nvidia-smi, use it.
if [[ -x "${AUTOTUNE_DIR}/bin/nvidia-smi" ]]; then
  export NVIDIA_SMI_BIN="${AUTOTUNE_DIR}/bin/nvidia-smi"
  export PATH="${AUTOTUNE_DIR}/bin:${PATH}"
fi

export AUTOSCHED_BIN
export HALIDE_DISTRIB_PATH
export SAMPLES_DIR="${SAMPLES_OUT}"

if [[ -z "${CXX:-}" ]]; then
  export CXX="c++"
fi

# ---------------------------------------------------------------------------
# Run autotune
# ---------------------------------------------------------------------------
if [[ -n "${GENERATOR_ARGS_SETS}" ]]; then
  /usr/bin/env bash "${LOOP_SCRIPT}" \
    "${GENERATOR}" \
    "${PIPELINE}" \
    "${HALIDE_TARGET}" \
    "${WEIGHTS_FILE}" \
    "${HALIDE_BUILD_DIR}" \
    "${PARALLELISM}" \
    "${TRAIN_ONLY}" \
    "${GENERATOR_ARGS_SETS}"
else
  /usr/bin/env bash "${LOOP_SCRIPT}" \
    "${GENERATOR}" \
    "${PIPELINE}" \
    "${HALIDE_TARGET}" \
    "${WEIGHTS_FILE}" \
    "${HALIDE_BUILD_DIR}" \
    "${PARALLELISM}" \
    "${TRAIN_ONLY}"
fi
